x-to-kafka-service:
  x-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: "Welcome to the x-to-kafka-service!"
  enable-v2-tweets: true
  enable-mock-tweets: false
  x-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  x-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  x-v2-bearer-token: ${TWITTER_BEARER_TOKEN}